name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            java_version: 8
          - os: ubuntu-22.04
            java_version: 11
          - os: ubuntu-22.04
            java_version: 17
          - os: macos-13
            java_version: 11
          - os: macos-14
            java_version: 11
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3.5.2
 
      - uses: actions/setup-java@v3.11.0
        with:
          distribution: zulu
          java-version: ${{ matrix.java_version }}

      - uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build --warning-mode=all
